### ISSUE TITLE
Create abstract implementation of all methods of SwingWorker that DiskWorker relies on

### ISSUE THREAD

**Issue by hamachshev** [hamachshev/lcmbadbm#3]
### Agile Story
As an agile developer who needs to enable DiskWorker to be independent  of SwingWorker, for all the reasons delineated in issue #2, I need to create an abstract implementation of the methods that DiskWorker relies on from SwingWorker so that instead of DiskWorker extending SwingWorker and thus being dependant, any class that implements said abstract version of the SwingWorker methods necessary will  be able to be passed into the constructor of DiskWorker and thus enable DiskWorker to run without being dependent on any **specific** UI Worker (Swing Worker or otherwise) implementation.

### Task List
In order to achieve said goal of creating an abstract implementation of all methods of SwingWorker that DiskWorker relies on, I will need to:
- [ ] Create a new interface and name the interface with a generic name (such as UIWorker) that signifies its ability to be a generic UI that the specific UIs, such as a CLI we can create in the future will implement
- [ ] Identify said methods that the new interface (henceforth called UIWorker) that I am creating will need to have . These methods have been identified as:  
#### In DiskWorker
- isCancelled (public final boolean isCancelled())
- setProgress (protected final void setProgress(int progress))
- publish (protected final void publish(V... chunks))
- get (public final T get() throws InterruptedException, ExecutionException())
#### In App
- cancel (public final boolean cancel(boolean mayInterruptIfRunning))
- addPropertyChangeListener (public final void addPropertyChangeListener(PropertyChangeListener listener))
- execute (public final void execute())

- [ ] Implement the  aforementioned methods in  the UI Worker interface; however, these methods must be renamed as to not clash with the class that extends SwingWorker and implements UIWorker  we will create (issue #5 )
