### ISSUE TITLE
Refractor DiscWorker and App to enable it to use the generic UIWorker Interface as opposed to its reliance on SwingWorker

### ISSUE THREAD

**Issue by hamachshev** [hamachshev/lcmbadbm#4]
### Agile Story
As an agile developer who needs to enable DiskWorker to be independent of SwingWorker, for all the reasons delineated in issue #2 , I need to refractor DiskWorker to be able to use the UIWorker instead of being reliant and extending SwingWorker.
### Task List
In order to accomplish the above, I need to:
- [ ] Remove DiscWorkers extendance of SwingWorker
- [ ] Add a UIWorker variable to the constructor of DiskWorker
- [ ] Add a private UIWorker instance variable to DiskWorker
- [ ] Init the instance variable in the constructor
- [ ] replace all the calls to all the methods (In DiskWorker) that have previously been  in SwingWorker (as delineated in #3 ) with calls to the instance variable's method's (and their changed, corresponding names)
- [ ] create the methods that App calls that used to be from SwingWorker (as deliniated in #3) in DiskWorker itself (these methods will call the instance variable UIWorker's methods)
- [ ] In App, rename the methods that used to be part of the SwingWorker Class and now are being called through the UIWorker interface to their updated names 
- [ ] In App, replace the DiskWorker instance variable constructor with `new Diskworker(UIWorker)` call
